config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', 
    path_names: { 
      sign_in: 'login', 
      sign_out: 'logout',
      edit: 'login_edit'
    }, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations"
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'pages#portfolio'
    end
    unauthenticated :user do
      root to: 'pages#welcome', as: :unauthenticated_root
    end
  end

  resources :users, :only => [:edit, :update]
  resources :currency_purchases, :only => [:index, :edit, :create, :update, :destroy]
  resources :currencies, :only => [:index]
  get 'search', to: 'currencies#search'
  get 'calculate', to: 'currencies#calculate'
  get 'currencies/:slug', to: 'currencies#show'

end

app/views/shared/_alerts.html.erb
<% if notice %>
    <div class="alert alert-primary alert-dismissible fade show m-0" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-primary alert-dismissible fade show m-0" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-custom">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Crypto Portfolio Manager", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <% if user_signed_in? %>
                <li class="nav-item"><%= active_link_to('Portfolio', root_path, class: 'nav-link', active: :exclusive) %></li>
                <li class="nav-item"><%= active_link_to('Currencies', currencies_path, class: 'nav-link') %></li>
                <li class="nav-item"><%= active_link_to('Account', edit_user_path(current_user), class: 'nav-link') %></li>
                <li class="nav-item"><%= active_link_to "Log Out", destroy_user_session_path, :method => :delete, class: 'nav-link' %></li>
            <% else %>
                <li class="nav-item"><%= active_link_to('Log In', new_user_session_path, class: 'nav-link') %></li>
                <li class="nav-item"><%= active_link_to('Sign up', new_user_registration_path, class: 'nav-link') %></li>
            <% end %>
        </ul>
    </div>
</nav>